blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

# from blog.views import

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import (
    MailingMessageListView, MailingMessageCreateView, MailingMessageUpdateView, MailingMessageDeleteView,
    MailingSettingsCreateView, MailingSettingsListView, MailingSettingsUpdateView, MailingSettingsDeleteView,
    MailingClientListView,
    ClientListView, ClientCreateView, ClientDeleteView, ClientUpdateView, toggle_client, index, MailingLogListView
)

app_name = MailingConfig.name

urlpatterns = [
    path('', index, name='index'),

    path('mailing_list/', MailingSettingsListView.as_view(), name='mailing_list'),
    path('create_mailing/', MailingSettingsCreateView.as_view(), name='create_mailing'),
    path('update_mailing/<int:pk>/', MailingSettingsUpdateView.as_view(), name='update_mailing'),
    path('delete_mailing/<int:pk>/', MailingSettingsDeleteView.as_view(), name='delete_mailing'),
    path('mailing_log/<int:pk>/', MailingLogListView.as_view(), name='mailing_log'),

    path('<int:pk>/clients', MailingClientListView.as_view(), name='mailing_clients_list'),
    path('<int:pk>/clients/add/<int:client_pk>/', toggle_client, name='mailing_clients_list_toggle'),

    path('clients/', ClientListView.as_view(), name='clients'),
    path('clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('clients/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('clients/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),

    path('message/', MailingMessageListView.as_view(), name='message'),
    path('message/create/', MailingMessageCreateView.as_view(), name='message_create'),
    path('message/update/<int:pk>/', MailingMessageUpdateView.as_view(), name='message_update'),
    path('message/delete/<int:pk>/', MailingMessageDeleteView.as_view(), name='message_delete'),

]

mailing/models.py
from django.conf import settings
from django.db import models

# Create your models here.

NULLABLE = {
    'blank': True,
    'null': True
}


class Client(models.Model):
    email = models.EmailField(verbose_name='email')
    client_name = models.CharField(max_length=150, verbose_name='фио')
    comment = models.TextField(verbose_name='комментарий')

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class MailingMessage(models.Model):
    subject = models.CharField(max_length=50, verbose_name='тема')
    text = models.TextField(verbose_name='текст')

    def __str__(self):
        return f'{self.subject}'

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'cooбщения'


class MailingSettings(models.Model):
    PERIOD_DAILY = 'daily'
    PERIOD_WEEKLY = 'weekly'
    PERIOD_MONTHLY = 'monthly'

    PERIODS = (
        (PERIOD_DAILY, 'Ежедневно'),
        (PERIOD_WEEKLY, 'Еженедельно'),
        (PERIOD_MONTHLY, 'Ежемесячно'),
    )

    STATUS_CREATED = 'created'
    STATUS_IN_PROCESS = 'in_process'
    STATUS_FINISHED = 'finished'

    STATUSES = (
        (STATUS_CREATED, 'Создано'),
        (STATUS_IN_PROCESS, 'В процессе'),
        (STATUS_FINISHED, 'Завершена'),
    )

    start_time = models.DateTimeField(verbose_name='время начала')
    end_time = models.DateTimeField(verbose_name='время окончания', **NULLABLE)
    period = models.CharField(max_length=20, choices=PERIODS, default=PERIOD_DAILY, verbose_name='период')
    status = models.CharField(max_length=20, choices=STATUSES, default=STATUS_CREATED, verbose_name='статус')

    message = models.ForeignKey(MailingMessage, on_delete=models.CASCADE, verbose_name='сообщение')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='владелец')

    def __str__(self):
        return f'{self.start_time} / {self.period}'

    class Meta:
        verbose_name = 'настройка'
        verbose_name_plural = 'настройки'



class MailingClient(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='клиент')
    settings = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, verbose_name='настройки')

    def __str__(self):
        return f'{self.client} / {self.settings}'

    class Meta:
        verbose_name = 'клиент рассылки'
        verbose_name_plural = 'клиенты рассылки'


class MailingLog(models.Model):
    STATUS_SUCCESS = 'success'
    STATUS_FAILED = 'failed'
    STATUSES = (
        (STATUS_SUCCESS, 'Успешно'),
        (STATUS_FAILED, 'Ошибка'),
    )

    last_try = models.DateTimeField(auto_now_add=True, verbose_name='дата последней попытки')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='клиент')
    settings = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, verbose_name='настройки')
    status = models.CharField(choices=STATUSES, default=STATUS_SUCCESS, verbose_name='статус')
    mail_service_response = models.TextField(**NULLABLE, verbose_name='ответ почтового сервиса')

    def __str__(self):
        return f'{self.last_try}'

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'

mailing/forms.py
from django import forms

from mailing.models import Client, MailingSettings, MailingMessage


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        fields = "__all__"


class MailSettingsForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingSettings
        exclude = ('owner',)

class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingMessage
        fields = "__all__"

mailing/views.py
import random

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from blog.models import Blog
from mailing.forms import MailSettingsForm, ClientForm, MessageForm
from mailing.models import MailingSettings, Client, MailingClient, MailingMessage, MailingLog
from mailing.services import get_random_blog, get_cached_data


# Settings

class MailingSettingsListView(LoginRequiredMixin, ListView):
    model = MailingSettings

    def get_queryset(self):
        queryset = super().get_queryset()

        if not self.request.user.is_staff:
            queryset = super().get_queryset().filter(owner=self.request.user)

        return queryset


class MailingSettingsCreateView(LoginRequiredMixin, CreateView):
    model = MailingSettings
    form_class = MailSettingsForm
    success_url = reverse_lazy('mailing:mailing_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class MailingSettingsUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = MailingSettings
    form_class = MailSettingsForm
    permission_required = 'mailing.change_mailingsettings'
    success_url = reverse_lazy('mailing:mailing_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user and not self.request.user.is_staff:
            raise Http404

        return self.object


class MailingSettingsDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = MailingSettings
    permission_required = 'mailing.delete_mailingsettings'
    success_url = reverse_lazy('mailing:mailing_list')


# Mail+Client


class MailingClientListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = MailingClient
    permission_required = 'mailing.view_mailingclient'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['clients'] = Client.objects.all()
        context_data['mailing_pk'] = self.kwargs.get('pk')

        return context_data


# Client


class ClientListView(LoginRequiredMixin, ListView):
    model = Client


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:clients')


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:clients')


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:clients')


# Message

class MailingMessageListView(LoginRequiredMixin, ListView):
    model = MailingMessage


class MailingMessageCreateView(LoginRequiredMixin, CreateView):
    model = MailingMessage
    form_class = MessageForm
    success_url = reverse_lazy('mailing:message')


class MailingMessageUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = MailingMessage
    form_class = MessageForm
    permission_required = 'mailing.change_mailingmessage'
    success_url = reverse_lazy('mailing:message')


class MailingMessageDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = MailingMessage
    permission_required = 'mailing.delete_mailingsettings'
    success_url = reverse_lazy('mailing:message')


class MailingLogListView(LoginRequiredMixin, ListView):
    model = MailingLog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = MailingLog.objects.filter(settings=self.kwargs.get('pk')).order_by('-last_try')
        return queryset

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['settings'] = MailingSettings.objects.get(pk=self.kwargs.get('pk'))
        return context_data


@login_required
def toggle_client(request, pk, client_pk):
    if MailingClient.objects.filter(
            client_id=client_pk,
            settings_id=pk
    ).exists():
        MailingClient.objects.filter(client_id=client_pk, settings_id=pk).delete()
    else:
        MailingClient.objects.create(client_id=client_pk, settings_id=pk)

    return redirect(reverse('mailing:mailing_clients_list', args=[pk]))


def index(request):
    total_mailings_counter, active_mailings_counter, unique_client_counter = get_cached_data()
    context = {
        'title': 'Главная',
        'total_mailings_counter': len(total_mailings_counter),
        'active_mailing_counter': len(active_mailings_counter),
        'unique_client_counter': len(unique_client_counter),
        'random_blog': get_random_blog(),
    }
    return render(request, 'mailing/index.html', context)


# def random_blogs(request):
#     items = list(Blog.objects.all())
#     random_items = random.sample(items, 3)
#     return render(request, 'news/posts.html', {'random_article': random_items})

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'mailing/includes/inc_main_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

{% block content%}
{% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Skychimp
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'mailing:mailing_list' %}">Рассылки</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
        </div>
    </footer>


<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
{% if user.is_authenticated %}
<div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Создать</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <p>Удалить публикацию?</p>
                        <button type="submit" class="btn btn-lg btn btn-primary">Подтвердить</button>
                        <a href="{% url 'mailing: clients' %}" class="btn btn-warning">Отмена</a>
                    </form>

                </div>
            </div>
        </div>
{% else %}
{% include 'mailing/includes/inc_need_authorization.html' %}
{% endif %}
{% endblock %}

mailing/templates/mailing/client_form.html
{% extends 'mailing/base.html' %}

{% block content %}
{% if user.is_authenticated %}
    <div class="col-12">
        <form class="row justify-content-md-center" method="post" enctype="multipart/form-data">

                <div class="col-3">
                    <div class="card mb-4">
                        <div class="card-header">
                            <h3 class="card-title">
                                {% if object %}
                                    Редактирование клиента
                                {% else %}
                                    Добавление нового клиента
                                {% endif %}
                            </h3>
                        </div>
                        <div class="card-body">

                            {% csrf_token %}
                            {{form.as_p}}
                            <button type="submit" class="btn btn-outline-success">Сохранить</button>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>


        </form>
    </div>
{% else %}
{% include 'mailing/includes/inc_need_authorization.html' %}
{% endif %}
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}
{% load my_tags %}



{% block content %}
{% if user.is_authenticated %}

<div class="container">
    <div class="col-12 mb-4">
        <a class="btn btn-outline-primary" href="{% url 'mailing:client_create' %}">Создать клиента</a>
    </div>

    <div class="row text-center">

        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                                    </div>

                <div class="card-body">
                    {% for object in object_list %}
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li> Категория: {{ object.email }}</li>
                    </ul>

                    <br>
                    <div class="btn-group">
                        <a class="btn btn-outline-secondary" href="{% url 'mailing:client_update' object.pk %}">Редактировать</a>
                        <a class="btn btn-outline-danger" href="{% url 'mailing:client_delete' object.pk %}">Удалить</a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>

    </div>
</div>
{% else %}
{% include 'mailing/includes/inc_need_authorization.html' %}
{% endif %}

    {% endblock %}

mailing/templates/mailing/index.html
{% extends 'mailing/base.html' %}
{% load my_tags %}


{% block content %}

<div class="container">

    <div class="row text-center">
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Количество рассылок всего</h4>
                    <br>
                </div>

                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ total_mailings_counter }}</h1>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Количество активных рассылок</h4>
                </div>

                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ active_mailing_counter }}</h1>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Количество уникальных клиентов</h4>
                </div>

                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ unique_client_counter }}</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <!--        {% if random_blog %}-->
        {% for object in random_blog %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">"{{ object.blog_title|title }}" ({{object.slug}})</h4>
                </div>
                <div class="card-body">
                    <p>{{ object.post | truncatechars:100 }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    Добавлен: {{ object.created_date }}
                    Просмотры: {{ object.view_count }}
                    <div class="d-flex justify-content-sm-end">
                        <a href="{% url 'blog:view' object.pk %}"
                           class="btn btn-sm btn-outline-secondary"> Подробнее</a>
                    </div>
                </div>

            </div>
        </div>
        {% endfor %}
        <!--        {% endif %}-->
    </div>
</div>


{% endblock %}

mailing/templates/mailing/mailingclient_list.html
{% extends 'mailing/base.html' %}
{% load my_tags %}


{% block content %}
{% if user.is_authenticated %}


<div class="col-12">
    <form class="row justify-content-md-center" method="post" enctype="multipart/form-data">

        <div class="col-3">
            <div class="card mb-4">
                <div class="card-header">
                    <h3 class="card-title">
                        Активные клиенты
                    </h3>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled">
                        {% for item in object_list %}
                        <li>
                            {{ item }}
                            <a class="float-end btn btn-outline-warning"
                               href="{% url 'mailing:mailing_clients_list_toggle' mailing_pk item.pk %}">
                                Убрать</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>

        <div class="col-3">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Неактивные клиенты
                    </h3>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled">
                        {% for item in clients %}
                        <li>
                            {{ item }}
                            <a class="float-end btn btn-outline-success"
                               href="{% url 'mailing:mailing_clients_list_toggle' mailing_pk item.pk %}">
                                Добавить</a>
                        </li>
                        {% endfor %}
                    </ul>

                </div>
                <div class="card-footer"></div>
            </div>
        </div>

    </form>
</div>
{% else %}
{% include 'mailing/includes/inc_need_authorization.html' %}
{% endif %}
{% endblock %}

mailing/templates/mailing/mailinglog_list.html
{% extends 'mailing/base.html' %}
{% load my_tags %}


{% block content %}
{% if user.is_authenticated %}


<div class="col-12">

    <div class="col-3">
        <div class="container">
            <h3>
                Статистика
            </h3>
        </div>

        {% if object_list %}
        {% for object in object_list %}

        <div class="container">
            <div class="row mb-3 text-center">
                <div class="col-4 themed-grid-col">{{ object.last_try }}</div>
                <div class="col-4 themed-grid-col">{{ object.status }}</div>
                <div class="col-4 themed-grid-col">{{ object.mail_service_response }}</div>
            </div>

        </div>
        {% endfor %}
        {% endif %}
    </div>

</div>
{% else %}
{% include 'mailing/includes/inc_need_authorization.html' %}
{% endif %}

{% endblock %}

mailing/templates/mailing/mailingmessage_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
{% if user.is_authenticated %}
<div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Удалить</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <p>Удалить сообщение?</p>
                        <button type="submit" class="btn btn-lg btn btn-primary">Подтвердить</button>
                        <a href="{% url 'mailing:index' %}" class="btn btn-warning">Отмена</a>
                    </form>

                </div>
            </div>
        </div>
{% else %}
{% include 'mailing/includes/inc_need_authorization.html' %}
{% endif %}
{% endblock %}

mailing/templates/mailing/mailingmessage_form.html
{% extends 'mailing/base.html' %}

{% block content %}
{% if user.is_authenticated %}
    <div class="col-12">
        <form class="row justify-content-md-center" method="post" enctype="multipart/form-data">

                <div class="col-3">
                    <div class="card mb-4">
                        <div class="card-header">
                            <h3 class="card-title">
                                {% if object %}
                                    Редактирование сообщения
                                {% else %}
                                    Добавление нового сообщения
                                {% endif %}
                            </h3>
                        </div>
                        <div class="card-body">

                            {% csrf_token %}
                            {{form.as_p}}
                            <button type="submit" class="btn btn-outline-success">Сохранить</button>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>


        </form>
    </div>
{% else %}
{% include 'mailing/includes/inc_need_authorization.html' %}
{% endif %}
{% endblock %}

mailing/templates/mailing/mailingmessage_list.html
{% extends 'mailing/base.html' %}
{% load my_tags %}



{% block content %}
{% if user.is_authenticated %}

<div class="container">
    <div class="col-12 mb-4">
        <a class="btn btn-outline-primary" href="{% url 'mailing:message_create' %}">Создать сообщение</a>
    </div>

    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">

                </div>

                <div class="card-body">

                    <ul class="list-unstyled mt-4 mb-4 text-start m-3">
                        <li> Сообщение: {{ object.subject }}</li>

                    </ul>
                    <br>
                    <div class="btn-group">
                        <a class="btn btn-outline-secondary" href="{% url 'mailing:message_update' object.pk %}">Редактировать</a>
                        <a class="btn btn-outline-danger" href="{% url 'mailing:message_delete' object.pk %}">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
{% include 'mailing/includes/inc_need_authorization.html' %}
{% endif %}

    {% endblock %}

mailing/templates/mailing/mailingsettings_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
{% if user.is_authenticated %}
<div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Создать</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <p>Удалить рассылку?</p>
                        <button type="submit" class="btn btn-lg btn btn-primary">Подтвердить</button>
                        <a href="{% url 'mailing:index' %}" class="btn btn-warning">Отмена</a>
                    </form>

                </div>
            </div>
        </div>
{% else %}
{% include 'mailing/includes/inc_need_authorization.html' %}
{% endif %}
{% endblock %}

mailing/templates/mailing/mailingsettings_form.html
{% extends 'mailing/base.html' %}

{% block content %}
{% if user.is_authenticated %}
    <div class="col-12">
        <form class="row justify-content-md-center" method="post" enctype="multipart/form-data">

                <div class="col-3">
                    <div class="card mb-4">
                        <div class="card-header">
                            <h3 class="card-title">
                                {% if object %}
                                    Редактирование рассылки
                                {% else %}
                                    Добавление новой рассылки
                                {% endif %}
                            </h3>
                        </div>
                        <div class="card-body">

                            {% csrf_token %}
                            {{form.as_p}}
                            <button type="submit" class="btn btn-outline-success">Сохранить</button>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>

        </form>
    </div>
{% else %}
{% include 'mailing/includes/inc_need_authorization.html' %}
{% endif %}
{% endblock %}

mailing/templates/mailing/mailingsettings_list.html
{% extends 'mailing/base.html' %}
{% load my_tags %}



{% block content %}
{% if user.is_authenticated %}

<div class="container">
    <div class="col-12 mb-4">
        <a class="btn btn-outline-primary" href="{% url 'mailing:create_mailing' %}">Создать рассылку</a>
    </div>

    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">

                </div>

                <div class="card-body">

                    <ul class="list-unstyled mt-4 mb-4 text-start m-3">
                        <li> Рассылка: {{ object.start_time }}</li>
                        <li> Владелец: {{ object.owner }}</li>

                    </ul>

                    <br>
                    <div class="btn-group">
                        {% if perms.mailing.change_mailingsettings %}
                        <a class="btn btn-outline-secondary" href="{% url 'mailing:update_mailing' object.pk %}">Редактировать</a>
                        {% endif %}
                        {% if perms.mailing.delete_mailingsettings %}
                        <a class="btn btn-outline-danger" href="{% url 'mailing:delete_mailing' object.pk %}">Удалить</a>
                        {% endif %}
                        <a class="btn btn-outline-info" href="{% url 'mailing:mailing_log' object.pk %}">История</a>
                    </div>
                    <div class="mt-1">
                        {% if perms.mailing.view_mailingclient %}
                        <a class="btn btn-outline-success" href="{% url 'mailing:mailing_clients_list' object.pk %}">Клиенты</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
{% include 'mailing/includes/inc_need_authorization.html' %}
{% endif %}

    {% endblock %}