blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

# from blog.views import

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from mailing.models import NULLABLE


# Create your models here.

class Blog(models.Model):
    blog_title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug')
    post = models.TextField(verbose_name='публикация')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='статус')
    view_count = models.IntegerField(default=0, verbose_name='просмотры')
    blog_image = models.ImageField(upload_to='blog/', **NULLABLE)


    def __str__(self):
        return f'{self.blog_title}'

    class Meta:
        verbose_name = 'публикация'
        verbose_name_plural = 'публикации'

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

# Create your views here.

from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blog


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ('blog_title', 'post', 'blog_image',)
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.blog_title)
            new_blog.save()

        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('blog_title', 'post', 'blog_image',)

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.blog_title)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
{% if user.is_authenticated %}
<div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Создать</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <p>Удалить публикацию {{object.blog_title}}?</p>
                        <button type="submit" class="btn btn-lg btn btn-primary">Подтвердить</button>
                        <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
                    </form>

                </div>
            </div>
        </div>
{% else %}
{% include 'mailing/includes/inc_need_authorization.html' %}
{% endif %}
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'mailing/base.html' %}
{% load my_tags %}

{% block content %}
{% if user.is_authenticated %}
<div class="album py-5 bg-light">
    <div class="container">

        <div class="row">
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">"{{ object.blog_title|title }}" ({{object.slug}})</h4>
                    </div>
                    <div class="card-body">
                        <img class="card-img-top" src="{{ object.blog_image|mediapath }}" alt="Card image cap">
                        <p>{{ object.post }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        Добавлен: {{ object.created_date }}
                        Просмотры: {{ object.view_count }}
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
{% else %}
{% include 'mailing/includes/inc_need_authorization.html' %}
{% endif %}
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mailing/base.html' %}


{% block content %}
{% if user.is_authenticated %}
<div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Создать</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}

                        <div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
{% else %}
{% include 'mailing/includes/inc_need_authorization.html' %}
{% endif %}
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailing/base.html' %}
{% load my_tags %}


{% block content %}
{% if user.is_authenticated %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blog:create' %}"> Добавить материал </a>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.blog_title|title }}</h4>
                </div>

                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'blog:view' object.pk %}"
                           class="btn btn-sm btn-outline-secondary"> View</a>
                        <a href="{% url 'blog:edit' object.pk %}"
                           class="btn btn-sm btn-outline-secondary"> Edit</a>
                        <a href="{% url 'blog:delete' object.pk %}"
                           class="btn btn-sm btn-outline-danger"> Delete</a>

                </div>
            </div>
        </div>

    </div>
        {% endfor %}
</div>
</div>
{% else %}
{% include 'mailing/includes/inc_need_authorization.html' %}
{% endif %}
    {% endblock %}