blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

# from blog.views import

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, verify_email_view, password_reset_view, UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verification/<int:key>/', verify_email_view, name='verification'),
    path('forgot_password/', password_reset_view, name='password_reset'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True,
            'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    country = models.CharField(max_length=35, verbose_name='страна', **NULLABLE)

    verification_key = models.IntegerField(verbose_name='ключ', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f"{self.email}"

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from mailing.forms import StyleFormMixin
from users.models import User


class RegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

class UserForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'phone', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from config import settings
from users.forms import UserForm, RegisterForm
from users.models import User


# Create your views here.

class LoginView(BaseLoginView):
    pass


class LogoutView(LoginRequiredMixin, BaseLogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = RegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('mailing:index')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save()

            self.object.is_active = False
            self.object.verification_key = ''.join([str(random.randint(0, 9)) for _ in range(0, 9)])
            self.object.save()
            send_mail(
                subject='Поздравляем с регистрацией!',
                message=f'Вы зарегистрировались на нашей площадке. Для подтверждения регистрации перейдите по ссылке: '
                        f'http://127.0.0.1:8000/users/verification/{self.object.verification_key}/',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[self.object.email]
            )

        return super().form_valid(form)


def verify_email_view(request, key):
    if request.method == 'GET':
        user = User.objects.get(verification_key=int(key))
        user.is_active = True
        user.save()

        context = {
            'object_list': User.objects.filter(verification_key=key)
        }

    return render(request, 'users/verification.html', context)


def password_reset_view(request):
    if request.method == 'POST':
        user = User.objects.get(email=request.POST.get('email'))
        new_password = User.objects.make_random_password()
        user.set_password(new_password)
        user.save()
        send_mail(
            subject='Сброс пароля',
            message=f'Вы запросили сброс пароля. Ваш новый пароль: {new_password}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[request.POST.get('email')]
        )
        return redirect('users:login')

    return render(request, 'users/reset_password.html')

class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    success_url = reverse_lazy('users:profile')
    form_class = UserForm

    def get_object(self, queryset=None):
        return self.request.user

users/templates/users/login.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-12">
        <form class="row justify-content-md-center" method="post" enctype="multipart/form-data">

                <div class="col-3">
                    <div class="card mb-4">
                        <div class="card-header">
                            <h3 class="card-title">
                                    Войти
                            </h3>
                        </div>
                        <div class="card-body">

                            {% csrf_token %}
                            {{form.as_p}}
                            <button type="submit" class="btn btn-outline-success">Войти</button>
                            <a href="{% url 'users:password_reset' %}" class="btn btn-outline-danger">Забыли пароль?</a>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
        </form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-12">
        <form class="row justify-content-md-center" method="post" enctype="multipart/form-data">

                <div class="col-3">
                    <div class="card mb-4">
                        <div class="card-header">
                            <h3 class="card-title">
                                    Регистрация
                            </h3>
                        </div>
                        <div class="card-body">

                            {% csrf_token %}
                            {{form.as_p}}
                            <button type="submit" class="btn btn-outline-success">Зарегистрироваться</button>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
        </form>
</div>
{% endblock %}

users/templates/users/reset_password.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-12">
        <form class="row justify-content-md-center" method="post" enctype="multipart/form-data">

                <div class="col-3">
                    <div class="card mb-4">
                        <div class="card-header">
                            <h3 class="card-title">
                                    Восстановить пароль
                            </h3>
                        </div>
                        <div class="card-body">

                            {% csrf_token %}
                            <input type="text" name="email" class="form-control" id="email" placeholder="Электронная почта" required>
                        <br>
                        <button type="submit" class="p-2 btn btn-outline-primary">Отправить</button>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
        </form>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-12">
        <form class="row justify-content-md-center" method="post" enctype="multipart/form-data">

                <div class="col-3">
                    <div class="card mb-4">
                        <div class="card-header">
                            <h3 class="card-title">
                                    Мой профиль
                            </h3>
                        </div>
                        <div class="card-body">

                            {% csrf_token %}
                            {{form.as_p}}
                            <button type="submit" class="btn btn-outline-success">Сохранить</button>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
        </form>
</div>
{% endblock %}

users/templates/users/verification.html
{% extends 'mailing/base.html' %}

{% block content %}


<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p class="card-text">Регистрация завершена успешно!</p>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}